#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := transmitter_hand_control

include $(IDF_PATH)/make/project.mk
