#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := receiver_control_dc_motor

include $(IDF_PATH)/make/project.mk
